### ISSUE TITLE
Speed of LMM

### ISSUE THREAD

**Issue by stonegold546** [agisga/mixed_models#11]
Hello,

I tried to run the LMM model with a dataset that has about 7000 cases, and it's taking me a few minutes to obtain the results. Is this typical?

Thanks a lot.

**Comment by agisga** [comment]
Unfortunately, depending on your setup and the model you are fitting, that's to be expected.
For a speedup you can check out @prasunanand's [JRuby port](https://github.com/prasunanand/mixed_models/tree/jruby_port) of mixed_models (also see his blog post [on NMatrix and JRuby](http://sciruby.com/blog/2016/10/24/gsoc-2016-port-nmatrix-to-jruby/)).

**Comment by prasunanand** [comment]
@stonegold546 ; You can also try to benchmark what is slow. I would recommend you to check the benchmark plots in my blog and are your benchmarks consistent with that in my blog.

Also, you can switch BLAS configurations to get the best results.

**Comment by stonegold546** [comment]
@agisga @prasunanand Thanks very much for the quick replies. I think I have a round-about alternative (OpenCPU) I will fall back on for now.
